// auto-generated
var _aggSymbols = {
    "left arrow": {Tag: Mi, output: "&larr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 1},
    "left right arrow": {Tag: Mi, output: "&harr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 2},
    "right arrow": {Tag: Mi, output: "&rarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 3},
    "map": {Tag: Mi, output: "&#8614;", family: "symbol", category: "Arrow", rank: 4},
    "inclusion map": {Tag: Mi, output: "&#8618;", family: "symbol", category: "Arrow", rank: 5},
    "left up harpoon": {Tag: Mi, output: "&#8636;", family: "symbol", category: "Arrow", rank: 6},
    "left down harpoon": {Tag: Mi, output: "&#8637;", family: "symbol", category: "Arrow", rank: 7},
    "right up harpoon": {Tag: Mi, output: "&#8640;", family: "symbol", category: "Arrow", rank: 8},
    "right down harpoon": {Tag: Mi, output: "&#8641;", family: "symbol", category: "Arrow", rank: 9},
    "left right harpoons": {Tag: Mi, output: "&#8651;", family: "symbol", category: "Arrow", rank: 10},
    "right left harpoons": {Tag: Mi, output: "&#8652;", family: "symbol", category: "Arrow", rank: 11},
    "left long arrow": {Tag: Mi, output: "&#10229;", family: "symbol", category: "Arrow", rank: 12},
    "left right long arrow": {Tag: Mi, output: "&#10231;", family: "symbol", category: "Arrow", rank: 13},
    "right long arrow": {Tag: Mi, output: "&#10230;", family: "symbol", category: "Arrow", rank: 14},
    "long map": {Tag: Mi, output: "&#10236;", family: "symbol", category: "Arrow", rank: 15},
    "northwest arrow": {Tag: Mi, output: "&#8598;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 16},
    "northeast arrow": {Tag: Mi, output: "&#8599;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 17},
    "southeast arrow": {Tag: Mi, output: "&#8600;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 18},
    "southwest arrow": {Tag: Mi, output: "&#8601;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 19},
    "up arrow": {Tag: Mi, output: "&uarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 20},
    "down arrow": {Tag: Mi, output: "&darr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 21},
    "left double arrow": {Tag: Mi, output: "&lArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 22},
    "left right double arrow": {Tag: Mi, output: "&hArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 23},
    "right double arrow": {Tag: Mi, output: "&rArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 24},
    "up double arrow": {Tag: Mi, output: "&uArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 25},
    "down double arrow": {Tag: Mi, output: "&dArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 26},
    "long left double arrow": {Tag: Mi, output: "&#10232;", family: "symbol", category: "Arrow", rank: 27},
    "long left right double arrow": {Tag: Mi, output: "&#10234;", family: "symbol", category: "Arrow", rank: 28},
    "long right double arrow": {Tag: Mi, output: "&#10233;", family: "symbol", category: "Arrow", rank: 29},
    "northwest double arrow": {Tag: Mi, output: "&#8662;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 30},
    "northeast double arrow": {Tag: Mi, output: "&#8663;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 31},
    "southeast double arrow": {Tag: Mi, output: "&#8664;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 32},
    "southwest double arrow": {Tag: Mi, output: "&#8665;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: 33},
    "dot operator": {Tag: Mi, output: "&#183;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 1},
    "times": {Tag: Mi, output: "&times;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 2},
    "composition": {Tag: Mi, output: "&#8728;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 5},
    "circled times": {Tag: Mi, output: "&otimes;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 6},
    "circled asterisk": {Tag: Mi, output: "&#8859;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 7},
    "circled division slash": {Tag: Mi, output: "&#8856;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 8},
    "circled ring": {Tag: Mi, output: "&#8858;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 9},
    "plus minus": {Tag: Mi, output: "&plusmn;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 10},
    "minus plus": {Tag: Mi, output: "&#8723;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 11},
    "dot plus": {Tag: Mi, output: "&#8724;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 12},
    "circled plus": {Tag: Mi, output: "&oplus;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 13},
    "circled minus": {Tag: Mi, output: "&#8854;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: 14},
    "left ceiling": {Tag: Mi, output: "&lceil;", family: "symbol", category: "Delimiter", rank: 1},
    "left floor": {Tag: Mi, output: "&lfloor;", family: "symbol", category: "Delimiter", rank: 2},
    "right ceiling": {Tag: Mi, output: "&rceil;", family: "symbol", category: "Delimiter", rank: 3},
    "right floor": {Tag: Mi, output: "&rfloor;", family: "symbol", category: "Delimiter", rank: 4},
    "angle": {Tag: Mi, output: "&ang;", family: "symbol", category: "Geometry", rank: 1},
    "measured angle": {Tag: Mi, output: "&#8737;", family: "symbol", category: "Geometry", rank: 2},
    "right angle with arc": {Tag: Mi, output: "&#8894;", family: "symbol", category: "Geometry", rank: 4},
    "spherical angle": {Tag: Mi, output: "&#8738;", family: "symbol", category: "Geometry", rank: 5},
    "angle divides": {Tag: Mi, output: "&#8739;", family: "symbol", category: "Geometry", rank: 6},
    "does not divide": {Tag: Mi, output: "&#8740;", family: "symbol", category: "Geometry", rank: 7},
    "parallel to": {Tag: Mi, output: "&#8741;", family: "symbol", category: "Geometry", rank: 8},
    "not parallel to": {Tag: Mi, output: "&#8742;", family: "symbol", category: "Geometry", rank: 9},
    "perpendicular": {Tag: Mi, output: "&perp;", family: "symbol", category: "Geometry", rank: 10},
    "down perpendicular": {Tag: Mi, output: "&#8868;", family: "symbol", category: "Geometry", rank: 11},
    "left perpendicular": {Tag: Mi, output: "&#8867;", family: "symbol", category: "Geometry", rank: 12},
    "right perpendicular": {Tag: Mi, output: "&#8866;", family: "symbol", category: "Geometry", rank: 13},
    "triangle": {Tag: Mi, output: "&#9651;", family: "symbol", category: "Geometry", rank: 14},
    "alpha": {Tag: Mi, output: "&alpha;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 1},
    "beta": {Tag: Mi, output: "&#x1d6fd;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 2},
    "gamma": {Tag: Mi, output: "&#x1d6fe;", css: {"padding":"0 .15em 0 0"}, family: "symbol", category: "Greek", rank: 3},
    "delta": {Tag: Mi, output: "&#x1d6ff;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 4},
    "epsilon": {Tag: Mi, output: "&#x1d700;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 5},
    "zeta": {Tag: Mi, output: "&#x1d701;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 6},
    "eta": {Tag: Mi, output: "&#x1d702;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 7},
    "theta": {Tag: Mi, output: "&#x1d703;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 8},
    "iota": {Tag: Mi, output: "&#x1d704;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 9},
    "kappa": {Tag: Mi, output: "&#x1d705;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 10},
    "lambda": {Tag: Mi, output: "&#x1d706;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 11},
    "mu": {Tag: Mi, output: "&#x1d707;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 12},
    "nu": {Tag: Mi, output: "&#x1d708;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 13},
    "xi": {Tag: Mi, output: "&#x1d709;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 14},
    "omicron": {Tag: Mi, output: "&#x1d70a;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 15},
    "pi": {Tag: Mi, output: "&#x1d70b;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 16},
    "rho": {Tag: Mi, output: "&#x1d70c;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 17},
    "sigma": {Tag: Mi, output: "&#x1d70e;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 18},
    "tau": {Tag: Mi, output: "&#x1d70f;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 19},
    "upsilon": {Tag: Mi, output: "&#x1d710;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 20},
    "phi": {Tag: Mi, output: "&#x1d711;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 21},
    "chi": {Tag: Mi, output: "&#x1d712;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 22},
    "psi": {Tag: Mi, output: "&#x1d713;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 23},
    "omega": {Tag: Mi, output: "&#x1d714;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 24},
    "Alpha": {Tag: Mi, output: "&#x391;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 25},
    "Beta": {Tag: Mi, output: "&#x392;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 26},
    "Gamma": {Tag: Mi, output: "&#x393;", css: {"padding":"0 .15em 0 0"}, family: "symbol", category: "Greek", rank: 27},
    "Delta": {Tag: Mi, output: "&#x394;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 28},
    "Epsilon": {Tag: Mi, output: "&#x395;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 29},
    "Zeta": {Tag: Mi, output: "&#x396;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 30},
    "Eta": {Tag: Mi, output: "&#x397;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 31},
    "Theta": {Tag: Mi, output: "&#x398;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 32},
    "Iota": {Tag: Mi, output: "&#x399;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 33},
    "Kappa": {Tag: Mi, output: "&#x39a;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 34},
    "Lambda": {Tag: Mi, output: "&#x39b;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 35},
    "Mu": {Tag: Mi, output: "&#x39c;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 36},
    "Nu": {Tag: Mi, output: "&#x39d;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 37},
    "Xi": {Tag: Mi, output: "&#x39e;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 38},
    "Omicron": {Tag: Mi, output: "&#x39f;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 39},
    "Pi": {Tag: Mi, output: "&#x3a0;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 40},
    "Rho": {Tag: Mi, output: "&#x3a1;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 41},
    "Sigma": {Tag: Mi, output: "&#x3a3;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 42},
    "Tau": {Tag: Mi, output: "&#x3a4;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 43},
    "Upsilon": {Tag: Mi, output: "&#x3a5;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 44},
    "Phi": {Tag: Mi, output: "&#x3a6;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 45},
    "Chi": {Tag: Mi, output: "&#x3a7;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 46},
    "Psi": {Tag: Mi, output: "&#x3a8;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 47},
    "Omega": {Tag: Mi, output: "&#x3a9;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek", rank: 48},
    "and": {Tag: Mi, output: "&and;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 1},
    "nand": {Tag: Mi, output: "&#8892;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 2},
    "curly and": {Tag: Mi, output: "&#8911;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 3},
    "or": {Tag: Mi, output: "&#8744;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 4},
    "nor": {Tag: Mi, output: "&#8893;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 5},
    "xor": {Tag: Mi, output: "&#8891;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 6},
    "curly or": {Tag: Mi, output: "&#8910;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 7},
    "not": {Tag: Mi, output: "&not;", family: "symbol", category: "Logic", rank: 8},
    "there exists": {Tag: Mi, output: "&exist;", family: "symbol", category: "Logic", rank: 9},
    "for all": {Tag: Mi, output: "&forall;", family: "symbol", category: "Logic", rank: 10},
    "there does not exist": {Tag: Mi, output: "&#8708;", family: "symbol", category: "Logic", rank: 11},
    "karp reduction": {Tag: Mi, output: "&#8826;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 12},
    "succeeds": {Tag: Mi, output: "&#8827;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 13},
    "because": {Tag: Mi, output: "&#8757;", family: "symbol", category: "Logic", rank: 14},
    "therefore": {Tag: Mi, output: "&there4;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: 15},
    "partial derivative": {Tag: Mi, output: "&part;", family: "symbol", category: "Operator", rank: 1},
    "nabla": {Tag: Mi, output: "&nabla;", family: "symbol", category: "Operator", rank: 2},
    "diamond operator": {Tag: Mi, output: "&#8900;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Operator", rank: 3},
    "Laplacian": {Tag: Mi, output: "&#8466;", family: "symbol", category: "Operator", rank: 5},
    "dots": {Tag: Mi, output: "&#8943;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: 1},
    "midline horizontal ellipsis": {Tag: Mi, output: "&#8943;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: 2},
    "down right diagonal ellipsis": {Tag: Mi, output: "&#8945;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: 3},
    "vertical ellipsis": {Tag: Mi, output: "&#8942;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: 4},
    "degree": {Tag: Mi, output: "&deg;", family: "symbol", category: "Punctuation", rank: 6},
    "end of proof": {Tag: Mi, output: "&#8718;", family: "symbol", category: "Punctuation", rank: 7},
    "similar": {Tag: Mi, output: "&sim;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 1},
    "asymptotic": {Tag: Mi, output: "&asymp;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 2},
    "asymptotically equal": {Tag: Mi, output: "&#8771;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 3},
    "approximately equal": {Tag: Mi, output: "&cong;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 4},
    "congruent": {Tag: Mi, output: "&cong;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 5},
    "equivalent": {Tag: Mi, output: "&equiv;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 6},
    "questioned equal": {Tag: Mi, output: "&#8799;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 7},
    "not equal": {Tag: Mi, output: "&ne;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 8},
    "not almost equal": {Tag: Mi, output: "&#8777;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 9},
    "not asymptotically equal": {Tag: Mi, output: "&#8772;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 10},
    "not identical": {Tag: Mi, output: "&#8802;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 11},
    "not equivalent": {Tag: Mi, output: "&#8802;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: 12},
    "proportion": {Tag: Mi, output: "&prop;", family: "symbol", category: "Relation", rank: 13},
    "less than or equal": {Tag: Mi, output: "&#8804;", family: "symbol", category: "Relation", rank: 14},
    "greater than or equal ": {Tag: Mi, output: "&#8805;", family: "symbol", category: "Relation", rank: 15},
    "double intersection": {Tag: Mi, output: "&#8915;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 3},
    "double union": {Tag: Mi, output: "&#8914;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 6},
    "proper subset": {Tag: Mi, output: "&sub;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 7},
    "subset": {Tag: Mi, output: "&sube;", family: "symbol", category: "Set", rank: 8},
    "double subset": {Tag: Mi, output: "&#8912;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 9},
    "not proper subset": {Tag: Mi, output: "&nsub;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 10},
    "not subset": {Tag: Mi, output: "&#8840;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 11},
    "proper superset": {Tag: Mi, output: "&sup;", family: "symbol", category: "Set", rank: 12},
    "subset not equal": {Tag: Mi, output: "&#8842;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 13},
    "superset": {Tag: Mi, output: "&supe;", family: "symbol", category: "Set", rank: 14},
    "double superset": {Tag: Mi, output: "&#8913;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 15},
    "not proper superset": {Tag: Mi, output: "&#8837;", family: "symbol", category: "Set", rank: 16},
    "not superset": {Tag: Mi, output: "&#8841;", family: "symbol", category: "Set", rank: 17},
    "element": {Tag: Mi, output: "&isin;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 18},
    "superset not equal": {Tag: Mi, output: "&#8843;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 19},
    "not element": {Tag: Mi, output: "&notin;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: 20},
    "contains": {Tag: Mi, output: "&ni;", family: "symbol", category: "Set", rank: 21},
    "not contains": {Tag: Mi, output: "&#8716;", family: "symbol", category: "Set", rank: 22},
    "multiset": {Tag: Mi, output: "&#8844;", family: "symbol", category: "Set", rank: 23},
    "natural numbers": {Tag: Mi, output: "&#8469;", family: "symbol", category: "Set", rank: 26},
    "integers": {Tag: Mi, output: "&#8484;", family: "symbol", category: "Set", rank: 27},
    "rational numbers": {Tag: Mi, output: "&#8474;", family: "symbol", category: "Set", rank: 28},
    "real numbers": {Tag: Mi, output: "&#8477;", family: "symbol", category: "Set", rank: 29},
    "complex numbers": {Tag: Mi, output: "&#8450;", family: "symbol", category: "Set", rank: 30},
    "prime numbers": {Tag: Mi, output: "&#8473;", family: "symbol", category: "Set", rank: 31},
    "whole numbers": {Tag: Mi, output: "&#120142;", family: "symbol", category: "Set", rank: 32},
    "irrational numbers": {Tag: Mi, output: "&#120128;", family: "symbol", category: "Set", rank: 33},
    "imaginary part": {Tag: Mi, output: "&image;", family: "symbol", category: "Set", rank: 34},
    "quaternion": {Tag: Mi, output: "&#8461;", family: "symbol", category: "Set", rank: 35},
    "real part": {Tag: Mi, output: "&real;", family: "symbol", category: "Set", rank: 36},
    "complement": {Tag: Mi, output: "&#8705;", family: "symbol", category: "Set", rank: 37},
    "aleph": {Tag: Mi, output: "&alefsym;", family: "symbol", category: "Set", rank: 38},
    "beth number": {Tag: Mi, output: "&#8502;", family: "symbol", category: "Set", rank: 39},
    "projective space": {Tag: Mi, output: "&#8473;", family: "symbol", category: "Set", rank: 40},
    "empty set": {Tag: Mi, output: "&empty;", family: "symbol", category: "Set", rank: 41},
    "set minus": {Tag: Mi, output: "&#8726;", css: {"padding":"0 .05em 0 .05em"}, family: "symbol", category: "Set", rank: 42},
    "infinity": {Tag: Mi, output: "&infin;", family: "symbol", category: "Special Character", rank: 1},
    "h bar": {Tag: Mi, output: "&#x210f;", family: "symbol", category: "Special Character", rank: 2},
    "Planck constant": {Tag: Mi, output: "&#x210e;", family: "symbol", category: "Special Character", rank: 3},
    "weierstrass power set": {Tag: Mi, output: "&weierp;", family: "symbol", category: "Special Character", rank: 4},
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
    "left arrow": {Tag: Mi, output: "&larr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "left right arrow": {Tag: Mi, output: "&harr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "right arrow": {Tag: Mi, output: "&rarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "map": {Tag: Mi, output: "&map;", family: "symbol", category: "Arrow"},
    "inclusion map": {Tag: Mi, output: "&hookrightarrow;", family: "symbol", category: "Arrow"},
    "left up harpoon": {Tag: Mi, output: "&leftharpoonup;", family: "symbol", category: "Arrow"},
    "left down harpoon": {Tag: Mi, output: "&leftharpoondown;", family: "symbol", category: "Arrow"},
    "right up harpoon": {Tag: Mi, output: "&rightharpoonup;", family: "symbol", category: "Arrow"},
    "right down harpoon": {Tag: Mi, output: "&rightharpoondown;", family: "symbol", category: "Arrow"},
    "left right harpoons": {Tag: Mi, output: "&leftrightharpoons;", family: "symbol", category: "Arrow"},
    "right left harpoons": {Tag: Mi, output: "&rightleftharpoons;", family: "symbol", category: "Arrow"},
    "left long arrow": {Tag: Mi, output: "&longleftarrow;", family: "symbol", category: "Arrow"},
    "left right long arrow": {Tag: Mi, output: "&longleftrightarrow;", family: "symbol", category: "Arrow"},
    "right long arrow": {Tag: Mi, output: "&longrightarrow;", family: "symbol", category: "Arrow"},
    "long map": {Tag: Mi, output: "&longmapsto;", family: "symbol", category: "Arrow"},
    "northwest arrow": {Tag: Mi, output: "&nwarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "northeast arrow": {Tag: Mi, output: "&nearr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "southeast arrow": {Tag: Mi, output: "&searr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "southwest arrow": {Tag: Mi, output: "&swarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "up arrow": {Tag: Mi, output: "&uarr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "down arrow": {Tag: Mi, output: "&darr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "left double arrow": {Tag: Mi, output: "&lArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "left right double arrow": {Tag: Mi, output: "&hArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "right double arrow": {Tag: Mi, output: "&rArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "up double arrow": {Tag: Mi, output: "&uArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "down double arrow": {Tag: Mi, output: "&dArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "long left double arrow": {Tag: Mi, output: "&Longleftarrow;", family: "symbol", category: "Arrow"},
    "long left right double arrow": {Tag: Mi, output: "&Longleftrightarrow;", family: "symbol", category: "Arrow"},
    "long right double arrow": {Tag: Mi, output: "&Longrightarrow;", family: "symbol", category: "Arrow"},
    "northwest double arrow": {Tag: Mi, output: "&nwArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "northeast double arrow": {Tag: Mi, output: "&neArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "southeast double arrow": {Tag: Mi, output: "&seArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "southwest double arrow": {Tag: Mi, output: "&swArr;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Arrow"},
    "dot operator": {Tag: Mi, output: "&centerdot;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "times": {Tag: Mi, output: "&times;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "composition": {Tag: Mi, output: "&compfn;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled times": {Tag: Mi, output: "&otimes;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled asterisk": {Tag: Mi, output: "&#8859;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled division slash": {Tag: Mi, output: "&#8856;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled ring": {Tag: Mi, output: "&#8858;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "plus minus": {Tag: Mi, output: "&plusmn;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "minus plus": {Tag: Mi, output: "&#8723;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "dot plus": {Tag: Mi, output: "&#8724;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled plus": {Tag: Mi, output: "&oplus;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled minus": {Tag: Mi, output: "&#8854;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "circled equals": {Tag: Mi, output: "&#8860;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator"},
    "left ceiling": {Tag: Mi, output: "&lceil;", family: "symbol", category: "Delimiter"},
    "left floor": {Tag: Mi, output: "&lfloor;", family: "symbol", category: "Delimiter"},
    "right ceiling": {Tag: Mi, output: "&rceil;", family: "symbol", category: "Delimiter"},
    "right floor": {Tag: Mi, output: "&rfloor;", family: "symbol", category: "Delimiter"},
    "angle": {Tag: Mi, output: "&ang;", family: "symbol", category: "Geometry"},
    "measured angle": {Tag: Mi, output: "&#8737;", family: "symbol", category: "Geometry"},
    "right angle": {Tag: Mi, output: "&#8735;", family: "symbol", category: "Geometry"},
    "right angle with arc": {Tag: Mi, output: "&#8894;", family: "symbol", category: "Geometry"},
    "spherical angle": {Tag: Mi, output: "&#8738;", family: "symbol", category: "Geometry"},
    "angle divides": {Tag: Mi, output: "&#8739;", family: "symbol", category: "Geometry"},
    "does not divide": {Tag: Mi, output: "&#8740;", family: "symbol", category: "Geometry"},
    "parallel to": {Tag: Mi, output: "&#8741;", family: "symbol", category: "Geometry"},
    "not parallel to": {Tag: Mi, output: "&#8742;", family: "symbol", category: "Geometry"},
    "perpendicular": {Tag: Mi, output: "&perp;", family: "symbol", category: "Geometry"},
    "down perpendicular": {Tag: Mi, output: "&#8868;", family: "symbol", category: "Geometry"},
    "left perpendicular": {Tag: Mi, output: "&#8867;", family: "symbol", category: "Geometry"},
    "right perpendicular": {Tag: Mi, output: "&#8866;", family: "symbol", category: "Geometry"},
    "triangle": {Tag: Mi, output: "&#9651;", family: "symbol", category: "Geometry"},
    "right triangle": {Tag: Mi, output: "&#8895;", family: "symbol", category: "Geometry"},
    "alpha": {Tag: Mi, output: "&#x1d6fc;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "beta": {Tag: Mi, output: "&#x1d6fd;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "gamma": {Tag: Mi, output: "&#x1d6fe;", css: {"padding":"0 .15em 0 0"}, family: "symbol", category: "Greek"},
    "delta": {Tag: Mi, output: "&#x1d6ff;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "epsilon": {Tag: Mi, output: "&#x1d700;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "zeta": {Tag: Mi, output: "&#x1d701;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "eta": {Tag: Mi, output: "&#x1d702;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "theta": {Tag: Mi, output: "&#x1d703;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "iota": {Tag: Mi, output: "&#x1d704;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "kappa": {Tag: Mi, output: "&#x1d705;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "lambda": {Tag: Mi, output: "&#x1d706;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "mu": {Tag: Mi, output: "&#x1d707;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "nu": {Tag: Mi, output: "&#x1d708;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "xi": {Tag: Mi, output: "&#x1d709;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "omicron": {Tag: Mi, output: "&#x1d70a;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "pi": {Tag: Mi, output: "&#x1d70b;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "rho": {Tag: Mi, output: "&#x1d70c;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "sigma": {Tag: Mi, output: "&#x1d70e;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "tau": {Tag: Mi, output: "&#x1d70f;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "upsilon": {Tag: Mi, output: "&#x1d710;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "phi": {Tag: Mi, output: "&#x1d711;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "chi": {Tag: Mi, output: "&#x1d712;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "psi": {Tag: Mi, output: "&#x1d713;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "omega": {Tag: Mi, output: "&#x1d714;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Alpha": {Tag: Mi, output: "&#x391;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Beta": {Tag: Mi, output: "&#x392;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Gamma": {Tag: Mi, output: "&#x393;", css: {"padding":"0 .15em 0 0"}, family: "symbol", category: "Greek"},
    "Delta": {Tag: Mi, output: "&#x394;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Epsilon": {Tag: Mi, output: "&#x395;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Zeta": {Tag: Mi, output: "&#x396;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Eta": {Tag: Mi, output: "&#x397;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Theta": {Tag: Mi, output: "&#x398;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Iota": {Tag: Mi, output: "&#x399;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Kappa": {Tag: Mi, output: "&#x39a;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Lambda": {Tag: Mi, output: "&#x39b;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Mu": {Tag: Mi, output: "&#x39c;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Nu": {Tag: Mi, output: "&#x39d;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Xi": {Tag: Mi, output: "&#x39e;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Omicron": {Tag: Mi, output: "&#x39f;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Pi": {Tag: Mi, output: "&#x3a0;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Rho": {Tag: Mi, output: "&#x3a1;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Sigma": {Tag: Mi, output: "&#x3a3;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Tau": {Tag: Mi, output: "&#x3a4;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Upsilon": {Tag: Mi, output: "&#x3a5;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Phi": {Tag: Mi, output: "&#x3a6;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Chi": {Tag: Mi, output: "&#x3a7;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Psi": {Tag: Mi, output: "&#x3a8;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "Omega": {Tag: Mi, output: "&#x3a9;", css: {"padding":"0 .05em 0 0"}, family: "symbol", category: "Greek"},
    "and": {Tag: Mi, output: "&and;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "nand": {Tag: Mi, output: "&#8892;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "curly and": {Tag: Mi, output: "&#8911;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "or": {Tag: Mi, output: "&#8744;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "nor": {Tag: Mi, output: "&#8893;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "xor": {Tag: Mi, output: "&#8891;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "curly or": {Tag: Mi, output: "&#8910;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "not": {Tag: Mi, output: "&not;", family: "symbol", category: "Logic"},
    "there exists": {Tag: Mi, output: "&exist;", family: "symbol", category: "Logic"},
    "for all": {Tag: Mi, output: "&forall;", family: "symbol", category: "Logic"},
    "there does not exist": {Tag: Mi, output: "&#8708;", family: "symbol", category: "Logic"},
    "karp reduction": {Tag: Mi, output: "&#8826;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "succeeds": {Tag: Mi, output: "&#8827;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "because": {Tag: Mi, output: "&#8757;", family: "symbol", category: "Logic"},
    "therefore": {Tag: Mi, output: "&there4;", css: {"padding":"0 .35em 0 .35em"}, family: "symbol", category: "Logic"},
    "partial derivative": {Tag: Mi, output: "&part;", family: "symbol", category: "Operator"},
    "nabla": {Tag: Mi, output: "&nabla;", family: "symbol", category: "Operator"},
    "diamond operator": {Tag: Mi, output: "&#8900;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Operator"},
    "Laplacian": {Tag: Mi, output: "&Laplacetrf;", family: "symbol", category: "Operator"},
    "dots": {Tag: Mi, output: "&ctdot;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation"},
    "midline horizontal ellipsis": {Tag: Mi, output: "&ctdot;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation"},
    "down right diagonal ellipsis": {Tag: Mi, output: "&dtdot;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation"},
    "vertical ellipsis": {Tag: Mi, output: "&vellip;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation"},
    "up right diagonal ellipsis": {Tag: Mi, output: "&utdot;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Punctuation"},
    "degree": {Tag: Mi, output: "&deg;", family: "symbol", category: "Punctuation"},
    "end of proof": {Tag: Mi, output: "&#8718;", family: "symbol", category: "Punctuation"},
    "similar": {Tag: Mi, output: "&sim;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "asymptotic": {Tag: Mi, output: "&asymp;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "asymptotically equal": {Tag: Mi, output: "&#8771;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "approximately equal": {Tag: Mi, output: "&cong;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "congruent": {Tag: Mi, output: "&cong;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "equivalent": {Tag: Mi, output: "&equiv;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "questioned equal": {Tag: Mi, output: "&questeq;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "not equal": {Tag: Mi, output: "&ne;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "not almost equal": {Tag: Mi, output: "&#8777;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "not asymptotically equal": {Tag: Mi, output: "&#8772;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "not identical": {Tag: Mi, output: "&#8802;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "not equivalent": {Tag: Mi, output: "&#8802;", css: {"padding":"0 .2em 0 .2em"}, family: "symbol", category: "Relation"},
    "proportion": {Tag: Mi, output: "&prop;", family: "symbol", category: "Relation"},
    "less than or equal": {Tag: Mi, output: "&leq;", family: "symbol", category: "Relation"},
    "greater than or equal ": {Tag: Mi, output: "&geq;", family: "symbol", category: "Relation"},
    "double intersection": {Tag: Mi, output: "&Cup;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "double union": {Tag: Mi, output: "&Cap;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "proper subset": {Tag: Mi, output: "&sub;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "subset": {Tag: Mi, output: "&sube;", family: "underover", category: "Set"},
    "double subset": {Tag: Mi, output: "&#8912;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "not proper subset": {Tag: Mi, output: "&nsub;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "not subset": {Tag: Mi, output: "&#8840;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "proper superset": {Tag: Mi, output: "&sup;", family: "underover", category: "Set"},
    "subset not equal": {Tag: Mi, output: "&#8842;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "superset": {Tag: Mi, output: "&supe;", family: "underover", category: "Set"},
    "double superset": {Tag: Mi, output: "&#8913;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "not proper superset": {Tag: Mi, output: "&nsup;", family: "underover", category: "Set"},
    "not superset": {Tag: Mi, output: "&#8841;", family: "underover", category: "Set"},
    "element": {Tag: Mi, output: "&isin;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "superset not equal": {Tag: Mi, output: "&#8843;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "not element": {Tag: Mi, output: "&notin;", css: {"padding":"0 .35em 0 .35em"}, family: "underover", category: "Set"},
    "contains": {Tag: Mi, output: "&ni;", family: "underover", category: "Set"},
    "not contains": {Tag: Mi, output: "&#8716;", family: "underover", category: "Set"},
    "multiset": {Tag: Mi, output: "&#8844;", family: "underover", category: "Set"},
    "multiset multiplication": {Tag: Mi, output: "&#8845;", family: "underover", category: "Set"},
    "multiset union": {Tag: Mi, output: "&#8846;", css: {"padding":"0 .2em 0 .2em"}, family: "underover", category: "Set"},
    "natural numbers": {Tag: Mi, output: "&#8469;", family: "underover", category: "Set"},
    "integers": {Tag: Mi, output: "&#8484;", family: "underover", category: "Set"},
    "rational numbers": {Tag: Mi, output: "&#8474;", family: "underover", category: "Set"},
    "real numbers": {Tag: Mi, output: "&#8477;", family: "underover", category: "Set"},
    "complex numbers": {Tag: Mi, output: "&#8450;", family: "underover", category: "Set"},
    "prime numbers": {Tag: Mi, output: "&primes;", family: "underover", category: "Set"},
    "whole numbers": {Tag: Mi, output: "&#120142;", family: "underover", category: "Set"},
    "irrational numbers": {Tag: Mi, output: "&#120128;", family: "underover", category: "Set"},
    "imaginary part": {Tag: Mi, output: "&image;", family: "underover", category: "Set"},
    "quaternion": {Tag: Mi, output: "&quaternions;", family: "underover", category: "Set"},
    "real part": {Tag: Mi, output: "&real;", family: "underover", category: "Set"},
    "complement": {Tag: Mi, output: "&#8705;", family: "underover", category: "Set"},
    "aleph": {Tag: Mi, output: "&alefsym;", family: "underover", category: "Set"},
    "beth number": {Tag: Mi, output: "&beth;", family: "underover", category: "Set"},
    "projective space": {Tag: Mi, output: "&#8473;", family: "underover", category: "Set"},
    "empty set": {Tag: Mi, output: "&empty;", family: "underover", category: "Set"},
    "set minus": {Tag: Mi, output: "&#8726;", css: {"padding":"0 .05em 0 .05em"}, family: "underover", category: "Set"},
    "infinity": {Tag: Mi, output: "&infin;", family: "underover", category: "Set"},
    "h bar": {Tag: Mi, output: "&#x210f;", family: "underover", category: "Set"},
    "Planck constant": {Tag: Mi, output: "&#x210e;", family: "underover", category: "Set"},
    "weierstrass power set": {Tag: Mi, output: "&weierp;", family: "underover", category: "Set"},
    null: null
}
