// auto-generated
var aggSymbols2 = {
        "left arrow": {Tag: Mi, output: "&larr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "1", latex: "\\leftarrow"},
    "right arrow": {Tag: Mi, output: "&rarr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "2", latex: "\\rightarrow"},
    "left right arrow": {Tag: Mi, output: "&harr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "3", latex: "\\leftrightarrow"},
    "map": {Tag: Mi, output: "&#8614;", family: "symbol", category: "Arrow", rank: "4", latex: "\\mapsto"},
    "inclusion map": {Tag: Mi, output: "&#8618;", family: "symbol", category: "Arrow", rank: "5", latex: "\\xhookrightarrow{}"},
    "left up harpoon": {Tag: Mi, output: "&#8636;", family: "symbol", category: "Arrow", rank: "6", latex: "\\leftharpoonup"},
    "left down harpoon": {Tag: Mi, output: "&#8637;", family: "symbol", category: "Arrow", rank: "7", latex: "\\leftharpoondown"},
    "right up harpoon": {Tag: Mi, output: "&#8640;", family: "symbol", category: "Arrow", rank: "8", latex: "\\rightharpoonup"},
    "right down harpoon": {Tag: Mi, output: "&#8641;", family: "symbol", category: "Arrow", rank: "9", latex: "\\rightharpoondown"},
    "left right harpoons": {Tag: Mi, output: "&#8651;", family: "symbol", category: "Arrow", rank: "10", latex: "\\leftrightharpoons"},
    "right left harpoons": {Tag: Mi, output: "&#8652;", family: "symbol", category: "Arrow", rank: "11", latex: "\\rightleftharpoons"},
    "left long arrow": {Tag: Mi, output: "&#10229;", family: "symbol", category: "Arrow", rank: "12", latex: "\\longleftarrow"},
    "left right long arrow": {Tag: Mi, output: "&#10231;", family: "symbol", category: "Arrow", rank: "13", latex: "\\longleftrightarrow"},
    "right long arrow": {Tag: Mi, output: "&#10230;", family: "symbol", category: "Arrow", rank: "14", latex: "\\longrightarrow"},
    "long map": {Tag: Mi, output: "&#10236;", family: "symbol", category: "Arrow", rank: "15", latex: "\\longmapsto"},
    "northwest arrow": {Tag: Mi, output: "&#8598;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "16", latex: "\\nwarrow"},
    "northeast arrow": {Tag: Mi, output: "&#8599;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "17", latex: "\\nearrow"},
    "southeast arrow": {Tag: Mi, output: "&#8600;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "18", latex: "\\searrow"},
    "southwest arrow": {Tag: Mi, output: "&#8601;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "19", latex: "\\swarrow"},
    "up arrow": {Tag: Mi, output: "&uarr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "20", latex: "\\uparrow"},
    "down arrow": {Tag: Mi, output: "&darr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "21", latex: "\\downarrow"},
    "left double arrow": {Tag: Mi, output: "&lArr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "22", latex: "\\Leftarrow"},
    "left right double arrow": {Tag: Mi, output: "&hArr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "23", latex: "\\Leftrightarrow"},
    "right double arrow": {Tag: Mi, output: "&rArr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "24", latex: "\\Rightarrow"},
    "up double arrow": {Tag: Mi, output: "&uArr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "25", latex: "\\Uparrow"},
    "down double arrow": {Tag: Mi, output: "&dArr;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "26", latex: "\\Downarrow"},
    "long left double arrow": {Tag: Mi, output: "&#10232;", family: "symbol", category: "Arrow", rank: "27", latex: "\\Longleftarrow"},
    "long left right double arrow": {Tag: Mi, output: "&#10234;", family: "symbol", category: "Arrow", rank: "28", latex: "\\Longleftrightarrow"},
    "long right double arrow": {Tag: Mi, output: "&#10233;", family: "symbol", category: "Arrow", rank: "29", latex: "\\Longrightarrow"},
    "northwest double arrow": {Tag: Mi, output: "&#8662;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "30", latex: "\\Nwarrow"},
    "northeast double arrow": {Tag: Mi, output: "&#8663;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "31", latex: "\\Nearrow"},
    "southeast double arrow": {Tag: Mi, output: "&#8664;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "32", latex: "\\Searrow"},
    "southwest double arrow": {Tag: Mi, output: "&#8665;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Arrow", rank: "33", latex: "\\Swarrow"},
    "dot operator": {Tag: Mi, output: "&#183;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "1", latex: "\\cdot"},
    "times": {Tag: Mi, output: "&times;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "2", latex: "\\times"},
    "composition": {Tag: Mi, output: "&#8728;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "5", latex: "\\circ"},
    "circled times": {Tag: Mi, output: "&otimes;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "6", latex: "\\otimes"},
    "circled asterisk": {Tag: Mi, output: "&#8859;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "7", latex: "\\circledast"},
    "circled division slash": {Tag: Mi, output: "&#8856;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "8", latex: "\\oslash"},
    "circled ring": {Tag: Mi, output: "&#8858;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "9", latex: "\\odot"},
    "plus minus": {Tag: Mi, output: "&plusmn;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "10", latex: "\\pm"},
    "minus plus": {Tag: Mi, output: "&#8723;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "11", latex: "\\mp"},
    "dot plus": {Tag: Mi, output: "&#8724;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "12", latex: "\\dotplus"},
    "circled plus": {Tag: Mi, output: "&oplus;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "13", latex: "\\oplus"},
    "circled minus": {Tag: Mi, output: "&#8854;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Binary Operator", rank: "14", latex: "\\circleddash"},
    "left ceiling": {Tag: Mi, output: "&lceil;", family: "symbol", category: "Delimiter", rank: "1", latex: "\\lceil"},
    "left floor": {Tag: Mi, output: "&lfloor;", family: "symbol", category: "Delimiter", rank: "2", latex: "\\lfloor"},
    "right ceiling": {Tag: Mi, output: "&rceil;", family: "symbol", category: "Delimiter", rank: "3", latex: "\\rceil"},
    "right floor": {Tag: Mi, output: "&rfloor;", family: "symbol", category: "Delimiter", rank: "4", latex: "\\rfloor"},
    "angle": {Tag: Mi, output: "&ang;", family: "symbol", category: "Geometry", rank: "1", latex: "\\angle"},
    "measured angle": {Tag: Mi, output: "&#8737;", family: "symbol", category: "Geometry", rank: "2", latex: "\\measuredangle"},
    "right angle with arc": {Tag: Mi, output: "&#8894;", family: "symbol", category: "Geometry", rank: "4", latex: "\\measuredangle"},
    "spherical angle": {Tag: Mi, output: "&#8738;", family: "symbol", category: "Geometry", rank: "5", latex: "\\sphericalangle"},
    "angle divides": {Tag: Mi, output: "&#8739;", family: "symbol", category: "Geometry", rank: "6", latex: "\|"},
    "does not divide": {Tag: Mi, output: "&#8740;", family: "symbol", category: "Geometry", rank: "7", latex: "\\nmid"},
    "parallel to": {Tag: Mi, output: "&#8741;", family: "symbol", category: "Geometry", rank: "8", latex: "\\parallel"},
    "not parallel to": {Tag: Mi, output: "&#8742;", family: "symbol", category: "Geometry", rank: "9", latex: "\\nparallel"},
    "perpendicular": {Tag: Mi, output: "&perp;", family: "symbol", category: "Geometry", rank: "10", latex: "\\perp"},
    "down perpendicular": {Tag: Mi, output: "&#8868;", family: "symbol", category: "Geometry", rank: "11", latex: "\\top"},
    "left perpendicular": {Tag: Mi, output: "&#8867;", family: "symbol", category: "Geometry", rank: "12", latex: "\\dashv"},
    "right perpendicular": {Tag: Mi, output: "&#8866;", family: "symbol", category: "Geometry", rank: "13", latex: "\\vdash"},
    "triangle": {Tag: Mi, output: "&#9651;", family: "symbol", category: "Geometry", rank: "14", latex: "\\triangle"},
    "alpha": {Tag: Mi, output: "&alpha;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "1", latex: "\\alpha"},
    "beta": {Tag: Mi, output: "&#x1d6fd;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "2", latex: "\\beta"},
    "gamma": {Tag: Mi, output: "&#x1d6fe;", css: {"padding": "0 .15em 0 0"}, family: "symbol", category: "Greek", rank: "3", latex: "\\gamma"},
    "delta": {Tag: Mi, output: "&#x1d6ff;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "4", latex: "\\delta"},
    "epsilon": {Tag: Mi, output: "&#x1d700;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "5", latex: "\\epsilon"},
    "zeta": {Tag: Mi, output: "&#x1d701;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "6", latex: "\\zeta"},
    "eta": {Tag: Mi, output: "&#x1d702;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "7", latex: "\\eta"},
    "theta": {Tag: Mi, output: "&#x1d703;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "8", latex: "\\theta"},
    "iota": {Tag: Mi, output: "&#x1d704;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "9", latex: "\\iota"},
    "kappa": {Tag: Mi, output: "&#x1d705;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "10", latex: "\\kappa"},
    "lambda": {Tag: Mi, output: "&#x1d706;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "11", latex: "\\lambda"},
    "mu": {Tag: Mi, output: "&#x1d707;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "12", latex: "\\mu"},
    "nu": {Tag: Mi, output: "&#x1d708;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "13", latex: "\\nu"},
    "xi": {Tag: Mi, output: "&#x1d709;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "14", latex: "\\xi"},
    "omicron": {Tag: Mi, output: "&#x1d70a;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "15", latex: "\\omicron"},
    "pi": {Tag: Mi, output: "&#x1d70b;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "16", latex: "\\pi"},
    "rho": {Tag: Mi, output: "&#x1d70c;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "17", latex: "\\rho"},
    "sigma": {Tag: Mi, output: "&#x1d70e;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "18", latex: "\\sigma"},
    "tau": {Tag: Mi, output: "&#x1d70f;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "19", latex: "\\tau"},
    "upsilon": {Tag: Mi, output: "&#x1d710;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "20", latex: "\\upsilon"},
    "phi": {Tag: Mi, output: "&#x1d711;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "21", latex: "\\phi"},
    "chi": {Tag: Mi, output: "&#x1d712;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "22", latex: "\\chi"},
    "psi": {Tag: Mi, output: "&#x1d713;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "23", latex: "\\psi"},
    "omega": {Tag: Mi, output: "&#x1d714;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "24", latex: "\\omega"},
    "Alpha": {Tag: Mi, output: "&#x391;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "25", latex: "\A"},
    "Beta": {Tag: Mi, output: "&#x392;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "26", latex: "\B"},
    "Gamma": {Tag: Mi, output: "&#x393;", css: {"padding": "0 .15em 0 0"}, family: "symbol", category: "Greek", rank: "27", latex: "\\Gamma"},
    "Delta": {Tag: Mi, output: "&#x394;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "28", latex: "\\Delta"},
    "Epsilon": {Tag: Mi, output: "&#x395;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "29", latex: "\E"},
    "Zeta": {Tag: Mi, output: "&#x396;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "30", latex: "\Z"},
    "Eta": {Tag: Mi, output: "&#x397;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "31", latex: "\H"},
    "Theta": {Tag: Mi, output: "&#x398;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "32", latex: "\\Theta"},
    "Iota": {Tag: Mi, output: "&#x399;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "33", latex: "\I"},
    "Kappa": {Tag: Mi, output: "&#x39a;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "34", latex: "\K"},
    "Lambda": {Tag: Mi, output: "&#x39b;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "35", latex: "\\Lambda"},
    "Mu": {Tag: Mi, output: "&#x39c;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "36", latex: "\M"},
    "Nu": {Tag: Mi, output: "&#x39d;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "37", latex: "\N"},
    "Xi": {Tag: Mi, output: "&#x39e;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "38", latex: "\\Xi"},
    "Omicron": {Tag: Mi, output: "&#x39f;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "39", latex: "\O"},
    "Pi": {Tag: Mi, output: "&#x3a0;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "40", latex: "\\Pi"},
    "Rho": {Tag: Mi, output: "&#x3a1;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "41", latex: "\P"},
    "Sigma": {Tag: Mi, output: "&#x3a3;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "42", latex: "\\Sigma"},
    "Tau": {Tag: Mi, output: "&#x3a4;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "43", latex: "\T"},
    "Upsilon": {Tag: Mi, output: "&#x3a5;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "44", latex: "\\Upsilon"},
    "Phi": {Tag: Mi, output: "&#x3a6;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "45", latex: "\\Phi"},
    "Chi": {Tag: Mi, output: "&#x3a7;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "46", latex: "\X"},
    "Psi": {Tag: Mi, output: "&#x3a8;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "47", latex: "\\Psi"},
    "Omega": {Tag: Mi, output: "&#x3a9;", css: {"padding": "0 .05em 0 0"}, family: "symbol", category: "Greek", rank: "48", latex: "\\Omega"},
    "curly and": {Tag: Mi, output: "&#8911;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: "3", latex: "\\curlywedge"},
    "curly or": {Tag: Mi, output: "&#8910;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: "7", latex: "\\curlyvee"},
    "not": {Tag: Mi, output: "&not;", family: "symbol", category: "Logic", rank: "8", latex: "\\neg"},
    "there exists": {Tag: Mi, output: "&exist;", family: "symbol", category: "Logic", rank: "9", latex: "\\exists"},
    "for all": {Tag: Mi, output: "&forall;", family: "symbol", category: "Logic", rank: "10", latex: "\\forall"},
    "there does not exist": {Tag: Mi, output: "&#8708;", family: "symbol", category: "Logic", rank: "11", latex: "\\nexists"},
    "karp reduction": {Tag: Mi, output: "&#8826;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: "12", latex: "\\prec"},
    "succeeds": {Tag: Mi, output: "&#8827;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: "13", latex: "\\succ"},
    "because": {Tag: Mi, output: "&#8757;", family: "symbol", category: "Logic", rank: "14", latex: "\\because"},
    "therefore": {Tag: Mi, output: "&there4;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Logic", rank: "15", latex: "\\therefore"},
    "partial derivative": {Tag: Mi, output: "&part;", family: "symbol", category: "Operator", rank: "1", latex: "\\partial"},
    "nabla": {Tag: Mi, output: "&nabla;", family: "symbol", category: "Operator", rank: "2", latex: "\\nabla"},
    "diamond operator": {Tag: Mi, output: "&#8900;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Operator", rank: "3", latex: "\\diamond"},
    "Laplacian": {Tag: Mi, output: "&#8466;", family: "symbol", category: "Operator", rank: "5", latex: "\\mathcal{L}"},
    "dots": {Tag: Mi, output: "&#8943;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: "1", latex: "\\dots"},
    "midline horizontal ellipsis": {Tag: Mi, output: "&#8943;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: "2", latex: "\\cdots"},
    "down right diagonal ellipsis": {Tag: Mi, output: "&#8945;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: "3", latex: "\\ddots"},
    "vertical ellipsis": {Tag: Mi, output: "&#8942;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Punctuation", rank: "4", latex: "\\vdots"},
    "degree": {Tag: Mi, output: "&deg;", family: "symbol", category: "Punctuation", rank: "6", latex: "\\degree"},
    "end of proof": {Tag: Mi, output: "&#8718;", family: "symbol", category: "Punctuation", rank: "7", latex: "\\blacksquare"},
    "similar": {Tag: Mi, output: "&sim;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "1", latex: "\\sim"},
    "asymptotic": {Tag: Mi, output: "&asymp;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "2", latex: "\\approx"},
    "asymptotically equal": {Tag: Mi, output: "&#8771;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "3", latex: "\\simeq"},
    "approximately equal": {Tag: Mi, output: "&cong;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "4", latex: "\\approxeq"},
    "congruent": {Tag: Mi, output: "&cong;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "5", latex: "\\cong"},
    "equivalent": {Tag: Mi, output: "&equiv;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "6", latex: "\\equiv"},
    "questioned equal": {Tag: Mi, output: "&#8799;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "7", latex: "\\overset{\\underset{\\mathrm{?}}{}}{=}"},
    "not equal": {Tag: Mi, output: "&ne;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "8", latex: "\\neq"},
    "not almost equal": {Tag: Mi, output: "&#8777;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "9", latex: "\\notapprox"},
    "not asymptotically equal": {Tag: Mi, output: "&#8772;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "10", latex: "\\notsimeq"},
    "not identical": {Tag: Mi, output: "&#8802;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "11", latex: "\\notequiv"},
    "not equivalent": {Tag: Mi, output: "&#8802;", css: {"padding": "0 .2em 0 .2em"}, family: "symbol", category: "Relation", rank: "12", latex: "\\nequiv"},
    "proportion": {Tag: Mi, output: "&prop;", family: "symbol", category: "Relation", rank: "13", latex: "\\propto"},
    "less than or equal": {Tag: Mi, output: "&#8804;", family: "symbol", category: "Relation", rank: "14", latex: "\\leq"},
    "intersection": {Tag: Mi, output: "&cap;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "1", latex: "\\bigcap"},
    "double intersection": {Tag: Mi, output: "&#8914;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "3", latex: "\\Cap"},
    "union": {Tag: Mi, output: "&cup;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "4", latex: "\\bigcup"},
    "double union": {Tag: Mi, output: "&#8915;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "7", latex: "\\Cup"},
    "proper subset": {Tag: Mi, output: "&sub;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "8", latex: "\\subset"},
    "subset": {Tag: Mi, output: "&sube;", family: "symbol", category: "Set", rank: "9", latex: "\\subseteq"},
    "double subset": {Tag: Mi, output: "&#8912;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "10", latex: "\\Subset"},
    "not proper subset": {Tag: Mi, output: "&nsub;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "11", latex: "\\notsubset"},
    "not subset": {Tag: Mi, output: "&#8840;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "12", latex: "\\notsubseteq"},
    "proper superset": {Tag: Mi, output: "&sup;", family: "symbol", category: "Set", rank: "13", latex: "\\supset"},
    "subset not equal": {Tag: Mi, output: "&#8842;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "14", latex: "\\subsetneq"},
    "superset": {Tag: Mi, output: "&supe;", family: "symbol", category: "Set", rank: "15", latex: "\\supseteq"},
    "double superset": {Tag: Mi, output: "&#8913;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "16", latex: "\\Supset"},
    "not proper superset": {Tag: Mi, output: "&#8837;", family: "symbol", category: "Set", rank: "17", latex: "\\notsupset"},
    "not superset": {Tag: Mi, output: "&#8841;", family: "symbol", category: "Set", rank: "18", latex: "\\notsupseteq"},
    "element": {Tag: Mi, output: "&isin;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "19", latex: "\\in"},
    "superset not equal": {Tag: Mi, output: "&#8843;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "20", latex: "\\supsetneq"},
    "not element": {Tag: Mi, output: "&notin;", css: {"padding": "0 .35em 0 .35em"}, family: "symbol", category: "Set", rank: "21", latex: "\\notin"},
    "contains": {Tag: Mi, output: "&ni;", family: "symbol", category: "Set", rank: "22", latex: "\\ni"},
    "not contains": {Tag: Mi, output: "&#8716;", family: "symbol", category: "Set", rank: "23", latex: "\\not\\ni"},
    "multiset": {Tag: Mi, output: "&#8844;", family: "symbol", category: "Set", rank: "24", latex: "\\uplus"},
    "natural numbers": {Tag: Mi, output: "&#8469;", family: "symbol", category: "Set", rank: "26", latex: "\\mathbb{N}"},
    "integers": {Tag: Mi, output: "&#8484;", family: "symbol", category: "Set", rank: "27", latex: "\\mathbb{Z}"},
    "rational numbers": {Tag: Mi, output: "&#8474;", family: "symbol", category: "Set", rank: "28", latex: "\\mathbb{Q}"},
    "real numbers": {Tag: Mi, output: "&#8477;", family: "symbol", category: "Set", rank: "29", latex: "\\mathbb{R}"},
    "complex numbers": {Tag: Mi, output: "&#8450;", family: "symbol", category: "Set", rank: "30", latex: "\\mathbb{C}"},
    "prime numbers": {Tag: Mi, output: "&#8473;", family: "symbol", category: "Set", rank: "31", latex: "\\mathbb{P}"},
    "whole numbers": {Tag: Mi, output: "&#120142;", family: "symbol", category: "Set", rank: "32", latex: "\\mathbb{W}"},
    "irrational numbers": {Tag: Mi, output: "&#120128;", family: "symbol", category: "Set", rank: "33", latex: "\\mathbb{I}"},
    "imaginary part": {Tag: Mi, output: "&image;", family: "symbol", category: "Set", rank: "34", latex: "\\Im"},
    "quaternion": {Tag: Mi, output: "&#8461;", family: "symbol", category: "Set", rank: "35", latex: "\\mathbb{H}"},
    "real part": {Tag: Mi, output: "&real;", family: "symbol", category: "Set", rank: "36", latex: "\\Re"},
    "complement": {Tag: Mi, output: "&#8705;", family: "symbol", category: "Set", rank: "37", latex: "\\complement"},
    "aleph": {Tag: Mi, output: "&alefsym;", family: "symbol", category: "Set", rank: "38", latex: "\\aleph"},
    "beth number": {Tag: Mi, output: "&#8502;", family: "symbol", category: "Set", rank: "39", latex: "\\beth"},
    "projective space": {Tag: Mi, output: "&#8473;", family: "symbol", category: "Set", rank: "40", latex: "\\mathbb{P}"},
    "empty set": {Tag: Mi, output: "&empty;", family: "symbol", category: "Set", rank: "41", latex: "\\emptyset"},
    "set minus": {Tag: Mi, output: "&#8726;", css: {"padding": "0 .05em 0 .05em"}, family: "symbol", category: "Set", rank: "42", latex: "\\setminus"},
    "infinity": {Tag: Mi, output: "&infin;", family: "symbol", category: "Special Character", rank: "1", latex: "\\infty"},
    "h bar": {Tag: Mi, output: "&#x210f;", family: "symbol", category: "Special Character", rank: "2", latex: "\\hslash"},
    "Planck constant": {Tag: Mi, output: "&#x210e;", family: "symbol", category: "Special Character", rank: "3", latex: "\h"},
    "weierstrass power set": {Tag: Mi, output: "&weierp;", family: "symbol", category: "Special Character", rank: "4", latex: "\\wp"}
};
