/**
 Export to JSON plugin for PHPMyAdmin
 @version 0.1
 MathX, All rights reserved.
 */

// Database 'mathx'
// mathx.symbols

var latexSymbols = {
    "infinity": {latex: "\\infty"},
    "times": {latex: "\\times"},     
    "alpha": {latex: "\\alpha"},
    "beta": {latex: "\\beta"},
    "gamma": {latex: "\\gamma"},
    "delta": {latex: "\\delta"},
    "epsilon": {latex: "\\epsilon"},
    "zeta": {latex: "\\zeta"},
    "eta": {latex: "\\eta"},
    "theta": {latex: "\\theta"},
    "iota": {latex: "\\iota"},
    "kappa": {latex: "\\kappa"},
    "superset": {latex: "\\supseteq"},
    "lambda": {latex: "\\lambda"},
    "mu": {latex: "\\mu"},
    "nu": {latex: "\\nu"},
    "subset": {latex: "\\subseteq"},
    "xi": {latex: "\\xi"},
    "omicron": {latex: "\\omicron"},
    "pi": {latex: "\\pi"},
    "not proper superset": {latex: "\\not\supset"},
    "rho": {latex: "\\rho"},
    "sigma": {latex: "\\sigma"},
    "not proper subset": {latex: "\\not\subset"},
    "tau": {latex: "\\tau"},
    "upsilon": {latex: "\\upsilon"},
    "phi": {latex: "\\phi"},
    "karp reduction": {latex: "\\prec"},
    "chi": {latex: "\\chi"},
    "psi": {latex: "\\psi"},
    "omega": {latex: "\\omega"},
    "proper superset": {latex: "\\supset"},
    "aleph": {latex: "\\aleph"},
    "therefore": {latex: "\\therefore"},
    "dot operator": {latex: "\\cdot"},
    "circled plus": {latex: "\\oplus"},
    "circled times": {latex: "\\otimes"},
    "degree": {latex: "\\degree"},
    "weierstrass power set": {latex: "\\wp"},
    "imaginary part": {latex: "\\Im"},
    "real part": {latex: "\\Re"},
    "real numbers": {latex: "\\mathbb{R}"},
    "complex numbers": {latex: "\\mathbb{C}"},
    "natural numbers": {latex: "\\mathbb{N}"},
    "rational numbers": {latex: "\\mathbb{Q}"},
    "integers": {latex: "\\mathbb{Z}"},
    "for all": {latex: "\\forall"},
    "complement": {latex: "\\complement"},
    "there exists": {latex: "\\exists"},
    "there does not exist": {latex: "\\nexists"},
    "empty set": {latex: "\\emptyset"},
    "not": {latex: "\\neg"},
    "and": {latex: "\\wedge"},
    "or": {latex: "\\vee"},
    "xor": {latex: "\\veebar"},
    "nand": {latex: "\\barwedge"},
    "nor": {latex: "\\overline{\vee}"},
    "partial derivative": {latex: "\\partial"},
    "element": {latex: "\\in"},
    "not element": {latex: "\\notin"},
    "contains": {latex: "\\ni"},
    "not contains": {latex: "\\not\\ni"},
    "set minus": {latex: "\\setminus"},
    "not subset": {latex: "\\not\subseteq"},
    "not superset": {latex: "\\not\supseteq"},
    "subset not equal": {latex: "\\subsetneq"},
    "superset not equal": {latex: "\\supsetneq"},
    "diamond operator": {latex: "\\diamond"},
    "asymptotically equal": {latex: "\\simeq"},
    "not asymptotically equal": {latex: "\\not\simeq"},
    "multiset": {latex: "\\uplus"},
    "double subset": {latex: "\\Subset"},
    "double superset": {latex: "\\Supset"},
    "double intersection": {latex: "\\Cap"},
    "double union": {latex: "\\Cup"},
    "proper subset": {latex: "\\subset"},
    "intersection": {latex: "\\cap"},
    "union": {latex: "\\cup"},
    "curly or": {latex: "\\curlyvee"},
    "curly and": {latex: "\\curlywedge"},
    "circled minus": {latex: "\\circleddash"},
    "circled division slash": {latex: "\\oslash"},
    "because": {latex: "\\because"},
    "proportion": {latex: "\\propto"},
    "end of proof": {latex: "\\blacksquare"},
    "angle": {latex: "\\angle"},
    "measured angle": {latex: "\\measuredangle"},
    "spherical angle": {latex: "\\sphericalangle"},
    "angle divides": {latex: "|"},
    "does not divide": {latex: "\\nmid"},
    "parallel to": {latex: "\\parallel"},
    "not parallel to": {latex: "\\nparallel"},
    "right angle with arc": {latex: "\\measuredangle"},
    "perpendicular": {latex: "\\perp"},
    "right perpendicular": {latex: "\\vdash"},
    "left perpendicular": {latex: "\\dashv"},
    "down perpendicular": {latex: "\\top"},
    "approximately equal": {latex: "\\approxeq"},
    "not almost equal": {latex: "\\not\approx"},
    "similar": {latex: "\\sim"},
    "not identical": {latex: "\\not\equiv"},
    "minus plus": {latex: "\\mp"},
    "dot plus": {latex: "\\dotplus"},
    "right arrow": {latex: "\\rightarrow"},
    "left arrow": {latex: "\\leftarrow"},
    "down arrow": {latex: "\\downarrow"},
    "up arrow": {latex: "\\uparrow"},
    "congruent": {latex: "\\cong"},
    "asymptotic": {latex: "\\approx"},
    "not equal": {latex: "\\neq"},
    "left ceiling": {latex: "\\lceil"},
    "right ceiling": {latex: "\\rceil"},
    "left floor": {latex: "\\lfloor"},
    "right floor": {latex: "\\rfloor"},
    "left right double arrow": {latex: "\\Leftrightarrow"},
    "left right arrow": {latex: "\\leftrightarrow"},
    "left double arrow": {latex: "\\Leftarrow"},
    "right double arrow": {latex: "\\Rightarrow"},
    "down double arrow": {latex: "\\Downarrow"},
    "up double arrow": {latex: "\\Uparrow"},
    "northeast arrow": {latex: "\\nearrow"},
    "northeast double arrow": {latex: "\\Nearrow"},
    "southeast arrow": {latex: "\\searrow"},
    "southeast double arrow": {latex: "\\Searrow"},
    "northwest arrow": {latex: "\\nwarrow"},
    "northwest double arrow": {latex: "\\Nwarrow"},
    "nabla": {latex: "\\nabla"},
    "projective space": {latex: "\\mathbb{P}"},
    "equivalent": {latex: "\\equiv"},
    "Planck constant": {latex: "h"},
    "not equivalent": {latex: "\\nequiv"},
    "plus minus": {latex: "\\pm"},
    "circled ring": {latex: "\\odot"},
    "circled asterisk": {latex: "\\circledast"},
    "ring": {latex: "\\circledcirc"},
    "beth number": {latex: "\\beth"},
    "Laplacian": {latex: "\\mathcal{L}"},
    "prime numbers": {latex: "\\mathbb{P}"},
    "quaternion": {latex: "\\mathbb{H}"},
    "succeeds": {latex: "\\succ"},
    "questioned equal": {latex: "\\overset{\\underset{\\mathrm{?}}{}}{=}"},
    "midline horizontal ellipsis": {latex: "\\cdots"},
    "dots": {latex: "\\dots"},
    "vertical ellipsis": {latex: "\\vdots"},
    "down right diagonal ellipsis": {latex: "\\ddots"},
    "composition": {latex: "\\circ"},
    "southwest arrow": {latex: "\\swarrow"},
    "southwest double arrow": {latex: "\\Swarrow"},
    "Alpha": {latex: "A"},
    "Beta": {latex: "B"},
    "Gamma": {latex: "\\Gamma"},
    "Delta": {latex: "\\Delta"},
    "Epsilon": {latex: "E"},
    "Zeta": {latex: "Z"},
    "Eta": {latex: "H"},
    "Theta": {latex: "\\Theta"},
    "Iota": {latex: "I"},
    "Kappa": {latex: "K"},
    "Lambda": {latex: "\\Lambda"},
    "Mu": {latex: "M"},
    "Nu": {latex: "N"},
    "Xi": {latex: "\\Xi"},
    "Omicron": {latex: "O"},
    "Pi": {latex: "\\Pi"},
    "Rho": {latex: "P"},
    "Sigma": {latex: "\\Sigma"},
    "Tau": {latex: "T"},
    "Upsilon": {latex: "\\Upsilon"},
    "Phi": {latex: "\\Phi"},
    "Chi": {latex: "X"},
    "Psi": {latex: "\\Psi"},
    "Omega": {latex: "\\Omega"},
    "intersection": {latex: "\\bigcap"},
    "limit": {latex: "\\lim"},
    "product": {latex: "\\prod"},
    "sum": {latex: "\\sum"},
    "coproduct": {latex: "\\coprod"},
    "root": {latex: "\\sqrt"},
    "cap product": {latex: "\\bigsqcap"},
    "cup product": {latex: "\\bigsqcup"},
    "direct sum": {latex: "\\bigoplus"},
    "sqrt": {latex: "\\sqrt"},
    "interior product": {latex: "\\bigvee"},
    "anticlockwise contour integral": {latex: "\\ointctrclockwise"},
    "clockwise contour integral": {latex: "\\varointclockwise"},
    "anticlockwise integral": {latex: "\\intctrclockwise"},
    "clockwise integral": {latex: "\\intclockwise"},
    "volume integral": {latex: "\\oiiint"},
    "surface integral": {latex: "\\oiint"},
    "contour integral": {latex: "\\oint"},
    "quadruple integral": {latex: "\\iiiint"},
    "triple integral": {latex: "\\iiint"},
    "double integral": {latex: "\\iint"},
    "integral": {latex: "\\int"},
    "union": {latex: "\\bigcup"},
    "tensor product": {latex: "\\bigotimes"},
    "wedge product": {latex: "\\bigwedge"},
    "ray": {latex: "\\overrightarrow"},
    "hat": {latex: "\\widehat"},
    "bar": {latex: "\\overline"},
    "dot": {latex: "\\dot"},
    "ddot": {latex: "\\ddot"},
    "tilde": {latex: "\\widetilde"},
    "line": {latex: "\\overleftrightarrow"},
    "vector": {latex: "\\overset{\rightharpoonup}"},
    "segment": {latex: "\\overline"},
    "less than or equal": {latex: "\\leq"},
    "greater than or equal": {latex: "\\geq"},
    "whole numbers": {latex: "\\mathbb{W}"},
    "irrational numbers": {latex: "\\mathbb{I}"},
    "arc": {latex: "\\stackrel{\frown}"},
    "triangle": {latex: "\\triangle"},
    "map": {latex: "\\mapsto"},
    "inclusion map": {latex: "\\xhookrightarrow{}"},
    "left up harpoon": {latex: "\\leftharpoonup"},
    "left down harpoon": {latex: "\\leftharpoondown"},
    "right up harpoon": {latex: "\\rightharpoonup"},
    "right down harpoon": {latex: "\\rightharpoondown"},
    "left right harpoons": {latex: "\\leftrightharpoons"},
    "right left harpoons": {latex: "\\rightleftharpoons"},
    "left long arrow": {latex: "\\longleftarrow"},
    "left right long arrow": {latex: "\\longleftrightarrow"},
    "right long arrow": {latex: "\\longrightarrow"},
    "long map": {latex: "\\longmapsto"},
    "long left double arrow": {latex: "\\Longleftarrow"},
    "long left right double arrow": {latex: "\\Longleftrightarrow"},
    "long right double arrow": {latex: "\\Longrightarrow"},
    "h bar": {latex: "\\hslash"}
};