var atomSymbols = [
    {input: /^[a-zA-Z]$/,    Tag: Mi},
    {input: /^[0-9.]$/,      Tag: Mn},
    {input: /^[\/+-<>|\\]$/, Tag: Mo},
    {input: '^',             Tag: Msup},
    {input: '_',             Tag: Msub}
];

var aggSymbols = {
    '<-':                 {Tag: Mo, output: '&larr;'},
    'leftarrow':          {Tag: Mo, output: '&larr;'},
    '->':                 {Tag: Mo, output: '&rarr;'},
    'rightarrow':         {Tag: Mo, output: '&rarr;'},
    '<->':                {Tag: Mo, output: '&harr;'},
    'leftrightarrow':     {Tag: Mo, output: '&harr;'},
    '|->':                {Tag: Mo, output: '&map;'},
    'map':                {Tag: Mo, output: '&map;'},
    '\\->':               {Tag: Mo, output: '&hookrightarrow;'},
    'inclusionmap':       {Tag: Mo, output: '&hookrightarrow;'},

    '<--':                {Tag: Mo, output: '&longleftarrow;'},
    'leftlongarrow':      {Tag: Mo, output: '&longleftarrow;'},
    '-->':                {Tag: Mo, output: '&longrightarrow;'},
    'rightlongarrow':     {Tag: Mo, output: '&longrightarrow;'},
    '<-->':               {Tag: Mo, output: '&longleftrightarrow;'},
    'leftrightlongarrow': {Tag: Mo, output: '&longleftrightarrow;'},
    '|-->':               {Tag: Mo, output: '&longmapsto;'},
    'longmap':            {Tag: Mo, output: '&longmapsto;'},

    'leftupharpoon':      {Tag: Mo, output: '&leftharpoonup;'},
    'leftdownharpoon':    {Tag: Mo, output: '&leftharpoondown;'},
    'rightupharpoon':     {Tag: Mo, output: '&rightharpoonup;'},
    'rightdownharpoon':   {Tag: Mo, output: '&rightharpoondown;'},
    'leftrightharpoon':   {Tag: Mo, output: '&leftrightharpoons;'},
    'rightleftharpoon':   {Tag: Mo, output: '&rightleftharpoons;'},

    'northwestarrow':     {Tag: Mo, output: '&nwarr;'},
    'northeastarrow':     {Tag: Mo, output: '&nearr;'},
    'southeastarrow':     {Tag: Mo, output: '&searr;'},
    'southwestarrow':     {Tag: Mo, output: '&swarr;'},
    'uparrow':            {Tag: Mo, output: '&uarr;'},
    'downarrow':          {Tag: Mo, output: '&darr;'},

    'leftdoublearrow':          {Tag: Mo, output: '&lArr;'},
    'rightdoublearrow':         {Tag: Mo, output: '&rArr;'},
    'leftrightdoublearrow':     {Tag: Mo, output: '&hArr;'},
    'updoublearrow':            {Tag: Mo, output: '&uArr;'},
    'downdoublearrow':          {Tag: Mo, output: '&dArr;'},

    'longleftdoublearrow':      {Tag: Mo, output: '&Longleftarrow;'},
    'longrightdoublearrow':     {Tag: Mo, output: '&Longrightarrow;'},
    'longleftrightdoublearrow': {Tag: Mo, output: '&Longleftrightarrow;'},

    'northwestdoublearrow':     {Tag: Mo, output: '&nwArr;'},
    'northeastdoublearrow':     {Tag: Mo, output: '&neArr;'},
    'southeastdoublearrow':     {Tag: Mo, output: '&seArr;'},
    'southwestdoublearrow':     {Tag: Mo, output: '&swArr;'},

    'dotproduct':           {Tag: Mo, output: '&centerdot;'},
    'times':                {Tag: Mo, output: '&times;'},
    'composition':          {Tag: Mo, output: '&compfn;'},
    'circledtimes':         {Tag: Mo, output: '&otimes;'},
    'circledasterisk':      {Tag: Mo, output: '&#8859;'},
    'circleddivisionslash': {Tag: Mo, output: '&#8856;'},
    'circledring':          {Tag: Mo, output: '&#8858;'},

    '+-':            {Tag: Mo, output: '&plusmn;'},
    'plusminus':     {Tag: Mo, output: '&plusmn;'},
    '-+':            {Tag: Mo, output: '&#8723;'},
    'minusplus':     {Tag: Mo, output: '&#8723;'},
    'dotplus':       {Tag: Mo, output: '&#8724;'},
    'circledplus':   {Tag: Mo, output: '&oplus;'},
    'circledminus':  {Tag: Mo, output: '&#8854;'},
    'circledequals': {Tag: Mo, output: '&#8860;'},

    'leftceiling':   {Tag: Mo, output: '&lceil;'},
    'leftfloor':     {Tag: Mo, output: '&lfloor;'},
    'rightceiling':  {Tag: Mo, output: '&rceil;'},
    'rightfloor':    {Tag: Mo, output: '&rfloor;'},

    'product':         {Tag: Munderover, output: '&prod;'},
    'coproduct':       {Tag: Munderover, output: '&coprod;'},
    'tensorproduct':   {Tag: Munderover, output: '&bigotimes;'},
    'wedgeproduct':    {Tag: Munderover, output: '&bigwedge;'},
    'interiorproduct': {Tag: Munderover, output: '&bigvee;'},
    'cupproduct':      {Tag: Munderover, output: '&bigsqcup;'},
    'capproduct':      {Tag: Munderover, output: '&sqcap;'},

    'sum':             {Tag: Munderover, output: '&Sum;'},
    'directsum':       {Tag: Munderover, output: '&#8853;'},

    'integral':                     {Tag: Msubsup, output: '&int;'},
    'doubleintegral':               {Tag: Msubsup, output: '&#8748;'},
    'tripleintegral':               {Tag: Msubsup, output: '&#8749;'},
    'quadrupleintegral':            {Tag: Msubsup, output: '&#10764;'},
    'clockwiseintegral':            {Tag: Msubsup, output: '&#8753;'},
    'anticlockwiseintegral':        {Tag: Msubsup, output: '&#10769;'},
    'contourintegral':              {Tag: Msubsup, output: '&#8750;'},
    'surfaceintegral':              {Tag: Msubsup, output: '&#8751;'},
    'volumeintegral':               {Tag: Msubsup, output: '&#8752;'},
    'clockwisecontourintegral':     {Tag: Msubsup, output: '&#8754;'},
    'anticlockwisecontourintegral': {Tag: Msubsup, output: '&#8755;'},

    'limit': {Tag: Munder, output: 'lim'},
    'sqrt': {Tag: Msqrt,  output: '&radic;', css: {padding: '0 0.2em 0 0'}}
};
