var atomSymbols = [
    {input: 'A', Tag: Mi, output: "&#x1d434;", css: {padding: '0 0 0 0'}},
    {input: 'B', Tag: Mi, output: "&#x1d435;", css: {padding: '0 .17em 0 0'}},
    {input: 'C', Tag: Mi, output: "&#x1d436;", css: {padding: '0 .1em 0 0'}},
    {input: 'D', Tag: Mi, output: "&#x1d437;", css: {padding: '0 .1em 0 0'}},
    {input: 'E', Tag: Mi, output: "&#x1d438;", css: {padding: '0 .12em 0 0'}},
    {input: 'F', Tag: Mi, output: "&#x1d439;", css: {padding: '0 .14em 0 0'}},
    {input: 'G', Tag: Mi, output: "&#x1d43a;", css: {padding: '0 .12em 0 0'}},
    {input: 'H', Tag: Mi, output: "&#x1d43b;", css: {padding: '0 .13em 0 0'}},
    {input: 'I', Tag: Mi, output: "&#x1d43c;", css: {padding: '0 .13em 0 0'}},
    {input: 'J', Tag: Mi, output: "&#x1d43d;", css: {padding: '0 .15em 0 0'}},
    {input: 'K', Tag: Mi, output: "&#x1d43e;", css: {padding: '0 .15em 0 0'}},
    {input: 'L', Tag: Mi, output: "&#x1d43f;", css: {padding: '0 .08em 0 0'}},
    {input: 'M', Tag: Mi, output: "&#x1d440;", css: {padding: '0 .13em 0 0'}},
    {input: 'N', Tag: Mi, output: "&#x1d441;", css: {padding: '0 .13em 0 0'}},
    {input: 'O', Tag: Mi, output: "&#x1d442;", css: {padding: '0 .11em 0 0'}},
    {input: 'P', Tag: Mi, output: "&#x1d443;", css: {padding: '0 .1em 0 0'}},
    {input: 'Q', Tag: Mi, output: "&#x1d444;", css: {padding: '0 .09em 0 0'}},
    {input: 'R', Tag: Mi, output: "&#x1d445;", css: {padding: '0 .03em 0 0'}},
    {input: 'S', Tag: Mi, output: "&#x1d446;", css: {padding: '0 .11em 0 0'}},
    {input: 'T', Tag: Mi, output: "&#x1d447;", css: {padding: '0 .14em 0 0'}},
    {input: 'U', Tag: Mi, output: "&#x1d448;", css: {padding: '0 .16em 0 0'}},
    {input: 'V', Tag: Mi, output: "&#x1d449;", css: {padding: '0 .16em 0 0'}},
    {input: 'W', Tag: Mi, output: "&#x1d44a;", css: {padding: '0 .16em 0 0'}},
    {input: 'X', Tag: Mi, output: "&#x1d44b;", css: {padding: '0 .16em 0 0'}},
    {input: 'Y', Tag: Mi, output: "&#x1d44c;", css: {padding: '0 .17em 0 0'}},
    {input: 'Z', Tag: Mi, output: "&#x1d44d;", css: {padding: '0 .17em 0 0'}},

    {input: 'a', Tag: Mi, output: "&#x1D44E;", css: {padding: '0 .08em 0 0'}},
    {input: 'b', Tag: Mi, output: "&#x1d44f;", css: {padding: '0 .1em 0 0'}},
    {input: 'c', Tag: Mi, output: "&#x1d450;", css: {padding: '0 .12em 0 0'}},
    {input: 'd', Tag: Mi, output: "&#x1d451;", css: {padding: '0 .1em 0 0'}},
    {input: 'e', Tag: Mi, output: "&#x1d452;", css: {padding: '0 .1em 0 0'}},
    {input: 'f', Tag: Mi, output: "&#x1d453;", css: {padding: '0 .15em 0 .13em'}},
    {input: 'g', Tag: Mi, output: "&#x1d454;", css: {padding: '0 .1em 0 .03em'}},
    {input: 'h', Tag: Mi, output: "&#8462;",   css: {padding: '0 .05em 0 0'}},
    {input: 'i', Tag: Mi, output: "&#x1d456;", css: {padding: '0 .1em 0 0'}},
    {input: 'j', Tag: Mi, output: "&#x1d457;", css: {padding: '0 .09em 0 .07em'}},
    {input: 'k', Tag: Mi, output: "&#x1d458;", css: {padding: '0 .1em 0 0'}},
    {input: 'l', Tag: Mi, output: "&#x1d459;", css: {padding: '0 .15em 0 0'}},
    {input: 'm', Tag: Mi, output: "&#x1d45a;", css: {padding: '0 .05em 0 0'}},
    {input: 'n', Tag: Mi, output: "&#x1d45b;", css: {padding: '0 .05em 0 0'}},
    {input: 'o', Tag: Mi, output: "&#x1d45c;", css: {padding: '0 .08em 0 0'}},
    {input: 'p', Tag: Mi, output: "&#x1d45d;", css: {padding: '0 .1em 0 .07em'}},
    {input: 'q', Tag: Mi, output: "&#x1d45e;", css: {padding: '0 .12em 0 0'}},
    {input: 'r', Tag: Mi, output: "&#x1d45f;", css: {padding: '0 .11em 0 0'}},
    {input: 's', Tag: Mi, output: "&#x1d460;", css: {padding: '0 .11em 0 0'}},
    {input: 't', Tag: Mi, output: "&#x1d461;", css: {padding: '0 .15em 0 0'}},
    {input: 'u', Tag: Mi, output: "&#x1d462;", css: {padding: '0 .08em 0 0'}},
    {input: 'v', Tag: Mi, output: "&#x1d463;", css: {padding: '0 .12em 0 0'}},
    {input: 'w', Tag: Mi, output: "&#x1d464;", css: {padding: '0 .1em 0 0'}},
    {input: 'x', Tag: Mi, output: "&#x1d465;", css: {padding: '0 .05em 0 0'}},
    {input: 'y', Tag: Mi, output: "&#x1d466;", css: {padding: '0 .06em 0 0'}},
    {input: 'z', Tag: Mi, output: "&#x1d467;", css: {padding: '0 .07em 0 0'}},

    {input: '<', Tag: Mo, css: {padding: '0 .2em'}},
    {input: '>', Tag: Mo, css: {padding: '0 .2em'}},
    {input: '*', Tag: Mo, css: {padding: '0 .2em'}},

    {input: /^[0-9.]$/,      Tag: Mn},
    {input: /^[\/+-|\\]$/,   Tag: Mo},
    {input: '^',             Tag: Msup},
    {input: '_',             Tag: Msub}
];

var aggSymbols = {
    '<-':                 {Tag: Mo, output: '&larr;'},
    '->':                 {Tag: Mo, output: '&rarr;'},
    '<->':                {Tag: Mo, output: '&harr;'},
    '|->':                {Tag: Mo, output: '&map;'},
    '\\->':               {Tag: Mo, output: '&hookrightarrow;'},

    '<--':                {Tag: Mo, output: '&longleftarrow;'},
    '-->':                {Tag: Mo, output: '&longrightarrow;'},
    '<-->':               {Tag: Mo, output: '&longleftrightarrow;'},
    '|-->':               {Tag: Mo, output: '&longmapsto;'},

    'del':                {Tag: Mi, output: '&part;'},
    'partial':            {Tag: Mi, output: '&part;'},
    'infinity':           {Tag: Mi, output: '&infin;'},
    'infty':              {Tag: Mi, output: '&infin;'},
    'grad':               {Tag: Mi, output: '&nabla;'},

    'only if':            {Tag: Mo, output: '&Longrightarrow;'},
    'and':                {Tag: Mo, output: '&and;'},
    'if':                 {Tag: Mo, output: '&Longleftarrow;'},

    'product':            {Tag: Munderover, output: '&prod;'},
    'coproduct':          {Tag: Munderover, output: '&coprod;'},
    'tensorproduct':      {Tag: Munderover, output: '&bigotimes;'},
    'wedgeproduct':       {Tag: Munderover, output: '&bigwedge;'},
    'interiorproduct':    {Tag: Munderover, output: '&bigvee;'},
    'cupproduct':         {Tag: Munderover, output: '&bigsqcup;'},
    'capproduct':         {Tag: Munderover, output: '&sqcap;'},

    'sum':                {Tag: Munderover, output: '&Sum;'},
    'directsum':          {Tag: Munderover, output: '&#8853;'},

    'integral':                     {Tag: Msubsup, output: '&int;'},
    'doubleintegral':               {Tag: Msubsup, output: '&#8748;'},
    'tripleintegral':               {Tag: Msubsup, output: '&#8749;'},
    'quadrupleintegral':            {Tag: Msubsup, output: '&#10764;'},
    'clockwiseintegral':            {Tag: Msubsup, output: '&#8753;'},
    'anticlockwiseintegral':        {Tag: Msubsup, output: '&#10769;'},
    'contourintegral':              {Tag: Msubsup, output: '&#8750;'},
    'surfaceintegral':              {Tag: Msubsup, output: '&#8751;'},
    'volumeintegral':               {Tag: Msubsup, output: '&#8752;'},
    'clockwisecontourintegral':     {Tag: Msubsup, output: '&#8754;'},
    'anticlockwisecontourintegral': {Tag: Msubsup, output: '&#8755;'},

    'lim':   {Tag: Munder, output: 'lim'},
    'limit': {Tag: Munder, output: 'lim'},
    'sqrt':  {Tag: Msqrt,  output: '&radic;', css: {padding: '0 0.2em 0 0'}},
    // 'root': {Tag: Msqrt,  output: '&radic;', css: {padding: '0 0.2em 0 0'}},

    'sin':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'sinh':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arcsin':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arcsinh': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'cos':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'cosh':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccos':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccosh': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'tan':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'tanh':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arctan':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arctanh': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'sec':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'sech':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arcsec':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arcsech': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'csc':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'csch':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccsc':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccsch': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'cot':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'coth':    {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccot':  {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'arccoth': {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},

    'log':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'mod':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'min':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'inf':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'sup':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'ln':      {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'gcd':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'max':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'det':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'lcm':     {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'Tr':      {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true},
    'tr':      {Tag: Mi, css: {padding: '0 0.1em 0 0'}, multiChar: true}
};

for (var key in _aggSymbols) {
    if (_aggSymbols.hasOwnProperty(key))
        aggSymbols[key] = _aggSymbols[key];
}
